# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.5'

gem 'jbuilder', '~> 2.7'
gem 'mysql2', '>= 0.4.4'
gem 'puma', '~> 5.5'
gem 'rack-cors'
gem 'rails', '~> 6.0.4', '>= 6.0.4.7'
gem 'ridgepole'

group :development, :test do
  gem 'pry-byebug'
end

group :development do
  gem 'breakman', require: false
  gem 'listen', '~> 3.3'
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end

group :test do
  gem 'rspec-rails'
  gem 'simplecov', require: false
end
